### ISSUE TITLE
how to change the picker background color?

### ISSUE THREAD

**Issue by pocesar** [DeweyReed/UltimateMusicPicker#12]
tried to use `music_picker_dialog_bg` with `tools:override="true"`, but didn't change anything. I'm using the `.goWithDialog(childFragmentManager)` method. I'm also using Material DayNight with night as default.

**Comment by DeweyReed** [comment]
Currently, this library can't change the picker background color to arbitrary color. To use AppCompat night mode, it should work out of the box.

**Comment by pocesar** [comment]
yeah, the background is off from my current color. maybe define a way to override the theme?

**Comment by DeweyReed** [comment]
I don't have a plan for that but you can create your own picker dialog by copying [this class](https://github.com/DeweyReed/UltimateMusicPicker/blob/master/library/src/main/java/xyz/aprildown/ultimatemusicpicker/MusicPickerDialog.kt). `MusicPickerActivity` and `MusicPickerDialog` simply are wrappers of `MusicPickerFragment`. Then you can edit the layout xml.

**Comment by pocesar** [comment]
yeah, that doesn't help, I would need to fork the entire project just to make that style change. all the companion is internal, and I can't just use the dialog file, there's 7 errors on the file just copying the content of the .kt file

**Comment by DeweyReed** [comment]
My bad. You can do something like this(I've verified it):

```Kotlin
class MusicPickerDialog : DialogFragment(), MusicPickerListener {

    private lateinit var musicPickerListener: MusicPickerListener

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setStyle(STYLE_NORMAL, R.style.UMP_Theme)
    }

    override fun onAttach(context: Context?) {
        super.onAttach(context)
        musicPickerListener = when {
            // In case using picker dialog in a fragment
            parentFragment is MusicPickerListener -> parentFragment as MusicPickerListener
            context is MusicPickerListener -> context
            activity is MusicPickerListener -> activity as MusicPickerListener
            else -> throw IllegalStateException("MusicPickerDialog requires a MusicPickerListener")
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val view = inflater.inflate(R.layout.dialog_music_picker, container, false)

        val header = view.findViewById<TextView>(R.id.textMusicHeader)
        arguments?.getString(EXTRA_WINDOW_TITLE).let {
            if (it.isNullOrBlank()) header.isGone = true else header.text = it
        }

        if (savedInstanceState == null) {
            childFragmentManager.beginTransaction()
                .replace(
                    R.id.layoutDialogMusicPicker, UltimateMusicPicker.createFragmentFromIntent(
                        UltimateMusicPicker().apply {
                            // init here
                        }.putSettingIntoIntent(Intent())
                    )
                )
                .commit()
        }
        return view
    }

    override fun onMusicPick(uri: Uri, title: String) {
        musicPickerListener.onMusicPick(uri, title)
        dismiss()
    }

    override fun onPickCanceled() {
        musicPickerListener.onPickCanceled()
        dismiss()
    }
}
```
The API isn't good but I've been working on v3.0.

**Comment by pocesar** [comment]
works great! also made it easier to work with picking for individual items without having to use a intent ❤️

**Comment by DeweyReed** [comment]
That's great!
I'm closing this issue. Free feel to reopen it if you have other questions.
