### ISSUE TITLE
Handle permission if user clicked "never ask again"

### ISSUE THREAD

**Issue by Naxomiun** [DeweyReed/UltimateMusicPicker#13]
Hi:

It would be very useful if it could handle internally when the user selects to never show again permission's dialog. Maybe some intent to the package settings to let the user enable it again because if permission is denied the dialog still showing but it wont let get anything from the internal storage and user wont get any explanation.

Greetings!

**Comment by DeweyReed** [comment]
Yes! I'm working on 3.0 this week which should open SAF if there is no permission.

**Comment by DeweyReed** [comment]
3.0.0 has an option to show SAF if the user denies permission or chooses "never ask again." It's on by default.

https://github.com/DeweyReed/UltimateRingtonePicker/releases/tag/3.0.0-alpha02
