### ISSUE TITLE
Random sound when file is erased from device

### ISSUE THREAD

**Issue by Naxomiun** [DeweyReed/UltimateMusicPicker#14]
I've noticed that if you select some audio file from the internal storage and then you delete it this library would play some default device notification noise. The ideal would be to check if the files you add on the library still existing on the device to avoid this. However, this is not really a problem because it doesn't throw any exception; just some enhancement!

Cheers!

**Comment by DeweyReed** [comment]
I think a broken icon for those missing files would be better. It won't confuse users.

I'll add it to 3.0. Thanks you!

**Comment by DeweyReed** [comment]
3.0.0 will show an error icon for ringtones unavailable, but it still depends on users to delete those custom ringtones.

https://github.com/DeweyReed/UltimateRingtonePicker/releases/tag/3.0.0-alpha02
