### ISSUE TITLE
why is the selected text too small

### ISSUE THREAD

**Issue by lambui09** [DeweyReed/UltimateMusicPicker#33]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/31691936/222920025-99126210-dbc9-4b0f-a2c3-06a10ab814ea.png">

**Comment by DeweyReed** [comment]
Is the long-press ripple of the buttons the normal size?

The button uses the Material Components style(https://github.com/DeweyReed/UltimateRingtonePicker/blob/master/library/src/main/res/layout/urp_activity_ringtone_picker.xml#L22). Did you adjust them in the app?

**Comment by lambui09** [comment]
I fixed, many thanks. have function support, when a ringstone selected. After restarting Activity ringtone, We can look item selected before
