### ISSUE TITLE
Does it support multi select?

### ISSUE THREAD

**Issue by andj207** [DeweyReed/UltimateMusicPicker#9]
Greate tool! Thanks for making this. My question is above, I wonder if it allows multiple selection and return the result list or not.

**Comment by DeweyReed** [comment]
@andj207 Unfortunately, it doesn't. What's its use cases? This may require some work.

**Comment by andj207** [comment]
My application has a feature allows user to pick multiple mp3 files to do some processing. I think some app might want to pick music files to process like merge/embed into other data or multi upload for example.

**Comment by DeweyReed** [comment]
@andj207 Thanks for the explanation. I'll figure out a way to support multi select. It might require some time.

**Comment by DeweyReed** [comment]
3.0.0 supports multi-select.

https://github.com/DeweyReed/UltimateRingtonePicker/releases/tag/3.0.0-alpha02
